In [3]:
import numpy as np

In [4]:
x_test=np.arange(2*5).reshape(2,5)
x_train=np.arange(4*5).reshape(4,5)

print(x_test)
print(x_train)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [11]:
print(x_train)
xx_train=x_train*2
print(xx_train)

print(x_train>6)
print(xx_train[x_train>6])
# print(x_train[])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]
[[False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[14 16 18 20 22 24 26 28 30 32 34 36 38]


In [4]:
num_test = x_test.shape[0]
num_train = x_train.shape[0]
dists = np.zeros((num_test, num_train))

for i in range(x_test.shape[0]):
    dists[i]=np.sqrt(np.sum(np.square(x_test[i]-x_train),axis=1))
print(dists)

[[ 13.56465997  10.44030651  16.85229955  26.62705391]
 [117.08543889 106.69582935  96.48315915  86.51011502]]


다시 공부 필요!!!!!

In [5]:
num_test = x_test.shape[0]
num_train = x_train.shape[0]
dists = np.zeros((num_test, num_train))

square_of_test=np.transpose([np.sum(np.square(x_test),axis=1)])
# square_of_test=np.sum(np.square(x_test),axis=1)

square_of_train=np.sum(np.square(x_train),axis=1)
mul=-2*np.dot(x_test,x_train.T)

print(square_of_test.shape)
print(square_of_train.shape)
print(mul.shape)


dists=np.sqrt(mul+square_of_test+square_of_train)
print(dists)

(2, 1)
(4,)
(2, 4)
[[ 13.56465997  10.44030651  16.85229955  26.62705391]
 [117.08543889 106.69582935  96.48315915  86.51011502]]


In [6]:
sample = [1,2,3]

[i for i in sample if i > 1]

[2, 3]